---
# Ansible playbook to configure Plex Media Server with Shoko Relay
# This assumes:
# - Plex Media Server is running directly on the host (not in Docker)
# - Shoko Server is running in a Docker container with port 8111 exposed to host
# - The setup follows the Shoko documentation: https://docs.shokoanime.com/plex/installing-agents-scanners
- name: Ensure Plex base directories exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: plex
    group: plex
    mode: "0775"
  loop:
    - "{{ plex_base_dir }}/Plug-ins"
    - "{{ plex_base_dir }}/Scanners"

- name: Stop Plex when installing Shoko Relay
  become: true
  service:
    name: "{{ plex_service_name }}"
    state: stopped

- name: Download and extract ShokoRelay.bundle
  become: true
  unarchive:
    src: "https://github.com/natyusha/ShokoRelay.bundle/releases/latest/download/ShokoRelay.bundle.tar.gz"
    dest: "{{ plex_base_dir }}/Plug-ins"
    remote_src: true
    creates: "{{ plex_base_dir }}/Plug-ins/ShokoRelay.bundle"
    owner: plex
    group: plex
    mode: "u=rwX,g=rwX,o=rX"

- name: Copy Shoko Relay Scanners to Plex base
  become: true
  copy:
    src: "{{ plex_base_dir }}/Plug-ins/ShokoRelay.bundle/Contents/Scanners"
    dest: "{{ plex_base_dir }}"
    remote_src: true
    owner: plex
    group: plex
    mode: "u=rwX,g=rwX,o=rX"

- name: Ensure Series scanners directory exists
  become: true
  file:
    path: "{{ plex_base_dir }}/Scanners/Series"
    state: directory
    owner: plex
    group: plex
    mode: "0775"

- name: Wait for Shoko server to be accessible
  uri:
    url: "http://{{ shoko_host }}:{{ shoko_port }}/api/init/status"
    method: GET
    status_code: [200, 401, 403]
  register: shoko_status
  until: shoko_status.status in [200, 401, 403]
  retries: 30
  delay: 10
  ignore_errors: true

- name: Display Shoko server status
  debug:
    msg: "Shoko server is {{ 'accessible' if shoko_status.status in [200, 401, 403] else 'not accessible' }} at {{ shoko_host }}:{{ shoko_port }}"

- name: Create Shoko Relay Scanner.cfg with preferences
  become: true
  copy:
    dest: "{{ plex_base_dir }}/Scanners/Series/Shoko Relay Scanner.cfg"
    owner: plex
    group: plex
    mode: "0644"
    content: |
      [Prefs]
      Hostname={{ shoko_host }}
      Port={{ shoko_port }}
      Username={{ shoko_username }}
      Password={{ shoko_password }}
      SingleSeasonOrdering={{ single_season_ordering | ternary('True','False') }}
      IncludeSpecials={{ include_specials | ternary('True','False') }}
      IncludeOther={{ include_other | ternary('True','False') }}

- name: Start Plex after configuring Shoko Relay
  become: true
  service:
    name: "{{ plex_service_name }}"
    state: started
