networks:
  ntfy:
    name: ntfy
    driver: bridge
    attachable: true

services:
  ntfy:
    image: binwiederhier/ntfy
    command:
      - serve
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/ntfy:/etc/ntfy
      - /var/cache/ntfy:/var/cache/ntfy
    networks:
      - ntfy
    ports:
      - 3434:80
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped